### ISSUE TITLE
【BUG】如果电机为非MIT模式，则示例代码会存在一点小问题

### ISSUE THREAD

**Issue by XuDL** [cmjang/DM_Control_Python#1]
假设电机为“位置速度”模式，则电机使能获参等ID也需要+0x100才可以正确使能电机，当前示例代码仅在control_Pos_Vel中对ID进行相加计算，而默认使能电机依然按原ID进行使能，就会导致无法正确使能的情况。
更好的模式或许是在连接上串口后，根据串口回传的信息判断当前电机模式，并完成ID计算。

非资深开发，如有用法不对提出了错误建议还请见谅。

**Comment by cmjang** [comment]
对的，这个是达妙老固件需要+0x100才可以正确使能电机，这周五会发布新固件，支持代码里面的修改参数等功能，使能也不需要加0x100.您的这个建议是正确的。新固件可以不用加这个，但是最好加上。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmjang/DM_Control_Python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 下午4:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cmjang/DM_Control_Python] 【BUG】如果电机为非MIT模式，则示例代码会存在一点小问题 (Issue #1)





 
假设电机为“位置速度”模式，则电机使能获参等ID也需要+0x100才可以正确使能电机，当前示例代码仅在control_Pos_Vel中对ID进行相加计算，而默认使能电机依然按原ID进行使能，就会导致无法正确使能的情况。
 更好的模式或许是在连接上串口后，根据串口回传的信息判断当前电机模式，并完成ID计算。
 
非资深开发，如有用法不对提出了错误建议还请见谅。

**Comment by cmjang** [comment]
修复完了 目前添加了enable_old模式，针对老固件，目前达妙的新固件已经发布了建议更新新固件
